language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_b2ecc706d1ba_key -iv $encrypted_b2ecc706d1ba_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
